apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        fsGroup: {{ .Values.pgid }}
      containers:
        - name: bazarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: {{ .Values.puid | quote }}
            - name: PGID
              value: {{ .Values.pgid | quote }}
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media
          persistentVolumeClaim:
            claimName: media-server-data
