controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: immich-postgres-rw
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-user
                key: password

valkey:
  enabled: true

immich:
  persistence:
    library:
      existingClaim: immich-library