apiVersion: v2
name: envoy-gateway
description: Envoy Gateway controller (Gateway API implementation)
type: application
version: 0.1.0

dependencies:
  - name: gateway-helm
    version: 1.8.3
    repository: oci://docker.io/envoyproxy