apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  labels:
    category: infra
spec:
  project: default
  source:
    repoURL: https://github.com/rverspaij/homelab
    targetRevision: main
    path: charts/infrastructure/adguard
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true