apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-gateways
  namespace: argocd
  labels:
    category: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rverspaij/homelab
    targetRevision: main
    path: charts/infrastructure/service-gateway/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true