longhorn:
  global:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  defaultSettings:
    defaultDataPath: /var/lib/longhorn

  persistence:
    defaultClassReplicaCount: 2

  preUpgradeChecker:
    jobEnabled: false
