gateway-helm:
  service:
    type: ClusterIP

routes:
  - name: argocd
    staticIP: "192.168.1.50"
    backendNamespace: argocd
    backendServiceName: argocd-server
    backendServicePort: 80
  - name: longhorn
    staticIP: "192.168.1.52"
    backendNamespace: longhorn-system
    backendServiceName: longhorn-frontend
    backendServicePort: 80
  - name: adguard
    staticIP: "192.168.1.51"
    backendNamespace: "adguard"
    backendServiceName: "adguard"
    backendServicePort: 3000