gateway-helm:
  service:
    type: ClusterIP

routes:
  - name: argocd
    hostname: argo.homelab
    staticIP: "192.168.1.50"
    backendNamespace: argocd
    backendServiceName: argocd-server
    backendServicePort: 80
  - name: longhorn
    hostname: longhorn.homelab
    staticIP: "192.168.1.52"
    backendNamespace: longhorn-system
    backendServiceName: longhorn-frontend
    backendServicePort: 80
  - name: adguard
    hostname: adguard.homelab
    staticIP: "192.168.1.53"
    backendNamespace: "adguard"
    backendServiceName: "adguard"
    backendServicePort: 80
  - name: immich
    hostname: immich.homelab
    staticIP: "192.168.1.54"
    backendNamespace: immich
    backendServiceName: immich-server
    backendServicePort: 2283
  - name: jellyfin
    hostname: jellyfin.homelab
    staticIP: "192.168.1.55"
    backendNamespace: "media"
    backendServiceName: "jellyfin"
    backendServicePort: 8096
  - name: sabnzbd
    hostname: sabnzbd.homelab
    staticIP: "192.168.1.56"
    backendNamespace: "media"
    backendServiceName: "sabnzbd"
    backendServicePort: 8080
  - name: prowlarr
    hostname: prowlarr.homelab
    staticIP: "192.168.1.57"
    backendNamespace: "media"
    backendServiceName: "prowlarr"
    backendServicePort: 9696
  - name: radarr
    hostname: radarr.homelab
    staticIP: "192.168.1.58"
    backendNamespace: "media"
    backendServiceName: "radarr"
    backendServicePort: 7878
  - name: sonarr
    hostname: sonarr.homelab
    staticIP: "192.168.1.59"
    backendNamespace: "media"
    backendServiceName: "sonarr"
    backendServicePort: 8989
  - name: seerr
    hostname: seerr.homelab
    staticIP: "192.168.1.60"
    backendNamespace: "media"
    backendServiceName: "seerr"
    backendServicePort: 5055
  - name: bazarr
    hostname: bazarr.homelab
    staticIP: "192.168.1.61"
    backendNamespace: "media"
    backendServiceName: "bazarr"
    backendServicePort: 6767