gateway-helm:
  service:
    type: ClusterIP

routes:
  - name: argocd
    hostname: argo.homelab
    staticIP: "192.168.1.50"
    backendNamespace: argocd
    backendServiceName: argocd-server
    backendServicePort: 80
  - name: longhorn
    hostname: longhorn.homelab
    staticIP: "192.168.1.52"
    backendNamespace: longhorn-system
    backendServiceName: longhorn-frontend
    backendServicePort: 80
  - name: adguard
    hostname: adguard.homelab
    staticIP: "192.168.1.53"
    backendNamespace: "adguard"
    backendServiceName: "adguard"
    backendServicePort: 80
  - name: immich
    hostname: immich.homelab
    staticIP: "192.168.1.54"
    backendNamespace: immich
    backendServiceName: immich-server
    backendServicePort: 2283
  - name: jellyfin
    hostname: jellyfin.homelab
    staticIP: "192.168.1.55"
    backendNamespace: "media"
    backendServiceName: "jellyfin"
    backendServicePort: 8096