apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgCtCHOG9ECjw8cth+EY0WpRt30dgLBf7DGTwaCfdXvdPbanbLjMoD9+br+QL71Osofja4qYmvqd+xu3o4Jo1M3o8McXy6hTnwCV8RDi56zam1ycmtlpABN3LYgB3CCkHeP7UkJilRBiCzrNRV+c1VQ1t6c74y3B26BCeGB4hq4NX4SOfzs08Gea4sX6XIIDuWNBRKDSTAMoe5oyX+FZNLdz7TmfuLaFFp7IiLhXovAE6b112lA0YG/9ZX16PEscDc/h/NTqMDd6pvusd1uT3CDa20JnbhUYKBcHDLuE2P0yuIIWu4hiCqHd/oRH745ip1XGPmdPDgkhyfFWl5vJ7fR6lXQD3H1566Zgl271CBSfm9Y+f64jK6jUIEHqinj1NFNUm5dZ/Xknl24Rc2Xd7Y+fNXnx7QkW1oQwWMEPNlAWD3e9vOpL7c0AveApucOJosbHjgvHYG8XHPKZahERNh3joMuWQV4i158OkEPAATpm2iUcjni4wyeULchAjfkFHOZBtwYUm1oiIz99K959S0dmvtagHX4xq6GoGvlhSh6r3qkKDgeDxDoI60EPNfrCmI6YwlbBlPlcQ0JHkjDuRUFVdzIleWjmccYLKvXRQUOsnqCWwJk9fgMEJebHmrzQRI7+uXrhgkcIJMMEo+adMoQ3enOvxGyJIg1bRxhT/YIylykiFhX+k3m8kdqyLvJPbXiBFDgmkqPFSrjx60z51ScrqVLgR+rwA9qWdhINsLBiYg==
    username: AgAWl8QxdGgjqIx2b1FlTgaM7wzuAR1KgbG2yKJB2d5mkPYf9gGdKKL/kTwp9XauXmsV34UwIQq8NX8mm2QPoU3sgrNrS7UGWKWyw9hKsZynIO+9u8Ei9N+jpj8on4dkHXTotjRJ8ZfwF8mWFC632gugONNe9SfJ/zKEqxkpHYmHaToTYX4Rc4qYPfUxvHTC9aTF/y4UHybiUrMb1nPosvh6HKwd4KWcJDwaViDrQh8tR8KyZnD7jdVhf1Wxu2iJToaM7g7q6NKPDdak0/HZgj3ox13m9wsDs7HA32w4kzy1v1IFthRrTaid6rT04EOWvnwqpQ7TVAAn5OdGJDyqVL/r89ai9cpalsMdEXVrp50ZYbpJBUGz4TGKPGC3kO2VlgTnir6Nh7L04l2IPpalzHTlkLChm/mtb2BAuTW6LpP6NhaqOjnTNAHXDJB2lEwpDN6WHTd+RmTRfC9MGyfA9bIVtStPimVlID4pwA+01CDyiM9nEAE9WUCVFuVogxYtZ8Jl/RWMN0Mt2tS7B7tu6Yg/HJLgkhB4ZlufBsTK3stP5ti6m8hfhGOp3r0v61+Y1+iWuyZABfuYm2mYhjblicgdmNZfTiiZxkFOixijeld6vqEO5gcOV/pcgTMSquL1vivfKJjTxwR0V6FCasyYis1ZeSf488qTNo5A8fGZfVlXPmqyGGkWBtsph1HdSJJOjQMz57hdRKY=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  imageName: tensorchord/cloudnative-vectorchord:16.9-0.4.3
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  enableSuperuserAccess: false
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
        passwordSecret:
          name: immich-postgres-user
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  storage:
    size: 20Gi
    storageClass: longhorn
