apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: "WA323719/Bv6OkmX0fCIQaB+OCJPZ5RX"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  imageName: tensorchord/cloudnative-vectorchord:16.9-0.4.3
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  enableSuperuserAccess: false
  managed:
    roles:
      - name: immich
        superuser: false
        login: true
        passwordSecret:
          name: immich-postgres-user
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  storage:
    size: 20Gi
    storageClass: longhorn
