apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: {{ .Values.pgid }}
      containers:
        - name: prowlarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: {{ .Values.puid | quote }}
            - name: PGID
              value: {{ .Values.pgid | quote }}
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
