argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      resource.customizations.ignoreDifferences.gateway.networking.k8s.io_HTTPRoute: |
        jqPathExpressions:
          - '.spec.parentRefs[].group'
          - '.spec.parentRefs[].kind'
          - '.spec.rules[].backendRefs[].group'
          - '.spec.rules[].backendRefs[].kind'
          - '.spec.rules[].backendRefs[].weight'